"""create tables

Revision ID: 751d235017f7
Revises:
Create Date: 2025-11-24 15:23:20.652944

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "751d235017f7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"transactions",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("amount", sa.Integer(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("(CURRENT_TIMESTAMP)"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(),
			server_default=sa.text("(CURRENT_TIMESTAMP)"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"users",
		sa.Column("id", sa.BigInteger(), nullable=False),
		sa.Column("name", sa.String(length=32), nullable=False),
		sa.Column("balance", sa.Integer(), server_default="0", nullable=False),
		sa.Column(
			"billing_date",
			sa.Date(),
			server_default=sa.text("(CURRENT_DATE)"),
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("(CURRENT_TIMESTAMP)"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(),
			server_default=sa.text("(CURRENT_TIMESTAMP)"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("users")
	op.drop_table("transactions")
	# ### end Alembic commands ###
