"""init db

Revision ID: 0153d1dcc890
Revises:
Create Date: 2025-12-07 13:14:18.457269

"""

from datetime import datetime, date, time
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0153d1dcc890"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# === НАСТРОЙКИ ===
PRICE_PER_30_DAYS = 100  # рублей за 30 дней подписки
DAILY_RATE = PRICE_PER_30_DAYS / 30.0  # рублей в день


def process_users():
	"""Перенос пользователей + расчёт баланса"""

	bind = op.get_bind()
	now = datetime.now()

	old_users = sa.table(
		"users",
		sa.column("id", sa.BigInteger),
		sa.column("username", sa.Text),
		sa.column("billing_start_date", sa.Date),
		sa.column("billing_end_date", sa.Date),
		sa.column("active", sa.Text),  # хранится как текст "true"/"false" или bool
	)

	users_result = bind.execute(sa.select(old_users)).fetchall()

	new_users_list = []

	# Конвертация значений
	for old_user in users_result:
		# ID сохраняется
		old_id = old_user.id

		# Имя
		username = old_user.username

		# billing_start_date → created_at (00:00:00)
		created_at = datetime.combine(old_user.billing_start_date or date.today(), time(0, 0))

		# Активность
		is_active_raw = old_user.active
		if isinstance(is_active_raw, str):
			is_active = is_active_raw.lower() in ("true", "1", "yes", "on")
		else:
			is_active = bool(is_active_raw)

		# === Расчёт баланса на основе оставшихся дней ===
		end_date = old_user.billing_end_date
		balance = 0

		if end_date and end_date >= date.today():
			days_left = (end_date - date.today()).days + 1  # включительно
			balance = round(days_left * DAILY_RATE)

		# Если подписка просрочена — баланс = 0
		if balance < 0:
			balance = 0

		new_users_list.append(
			{
				"id": old_id,
				"name": username,
				"is_active": is_active,
				"balance": balance,
				"created_at": created_at,
				"updated_at": now,
			}
		)

	# удаление старой таблицы
	op.drop_table("users")

	# создание новой таблицы
	users_table = op.create_table(
		"users",
		sa.Column("id", sa.BigInteger(), nullable=False),
		sa.Column("name", sa.String(length=32), nullable=False),
		sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
		sa.Column("balance", sa.Integer(), server_default="0", nullable=False),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
		sa.UniqueConstraint("name", name=op.f("uq_users_name")),
	)

	if new_users_list:
		op.bulk_insert(users_table, new_users_list)


def process_transactions():
	"""Перенос транзакций"""

	bind = op.get_bind()
	now = datetime.now()

	# структура старой таблицы
	old_transactions = sa.table(
		"transactions",
		sa.column("id", sa.Integer),
		sa.column("user_id", sa.BigInteger),
		sa.column("transaction_date", sa.Date),
		sa.column("amount", sa.Integer),
	)

	# чтение значений старой таблицы
	trans_result = bind.execute(sa.select(old_transactions)).fetchall()

	new_transactions_list = []

	# конвертация значений
	for t in trans_result:
		trans_date = t.transaction_date or date.today()
		created_at = datetime.combine(trans_date, time(0, 0))

		new_transactions_list.append(
			{
				"user_id": t.user_id,
				"amount": t.amount,
				"created_at": created_at,
				"updated_at": now,
			}
		)
	# удаление старой таблицы
	op.drop_table("transactions")
	# создание новой таблицы
	transactions_table = op.create_table(
		"transactions",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.BigInteger(), nullable=True),
		sa.Column("amount", sa.Integer(), nullable=False),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.ForeignKeyConstraint(
			["user_id"], ["users.id"], name=op.f("fk_transactions_user_id_users"), ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
	)
	if new_transactions_list:
		op.bulk_insert(transactions_table, new_transactions_list)


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	process_users()
	process_transactions()
	op.drop_table("awg")
	op.drop_table("vless")
	op.drop_table("messages")
	op.drop_table("notifications")

	op.create_table(
		"awg",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("ip", sa.String(), nullable=False),
		sa.Column("mask", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.BigInteger(), nullable=False),
		sa.Column("public_key", sa.String(), nullable=False),
		sa.Column("private_key", sa.String(), nullable=False),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_awg_user_id_users")),
		sa.PrimaryKeyConstraint("id", name=op.f("pk_awg")),
		sa.UniqueConstraint("ip", name=op.f("uq_awg_ip")),
	)
	op.create_table(
		"messages",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("chat_id", sa.BigInteger(), nullable=False),
		sa.Column("text", sa.String(), nullable=False),
		sa.Column(
			"status",
			sa.Enum(
				"PENDING", "SENT", "CHAT_NOT_EXIST", "BOT_BLOCKED", "API_ERROR", "UNKNOWN_ERROR", name="messagestatus"
			),
			server_default="Ждет отправки",
			nullable=False,
		),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.ForeignKeyConstraint(["chat_id"], ["users.id"], name=op.f("fk_messages_chat_id_users"), ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
	)

	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("transactions")
	op.drop_table("messages")
	op.drop_table("awg")
	op.drop_table("users")
	# ### end Alembic commands ###
