"""create tables

Revision ID: 19dd62cceb0c
Revises:
Create Date: 2025-12-06 14:33:23.956192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19dd62cceb0c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"users",
		sa.Column("id", sa.BigInteger(), nullable=False),
		sa.Column("name", sa.String(length=32), nullable=False),
		sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
		sa.Column("balance", sa.Integer(), server_default="0", nullable=False),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
		sa.UniqueConstraint("name", name=op.f("uq_users_name")),
	)
	op.create_table(
		"awg",
		sa.Column("id", sa.BigInteger(), nullable=False),
		sa.Column("ip", sa.String(), nullable=False),
		sa.Column("mask", sa.Integer(), nullable=False),
		sa.Column("public_key", sa.String(), nullable=False),
		sa.Column("private_key", sa.String(), nullable=False),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.ForeignKeyConstraint(["id"], ["users.id"], name=op.f("fk_awg_id_users"), ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id", name=op.f("pk_awg")),
	)
	op.create_table(
		"messages",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("chat_id", sa.BigInteger(), nullable=False),
		sa.Column("text", sa.String(), nullable=False),
		sa.Column(
			"status",
			sa.Enum(
				"PENDING", "SENT", "CHAT_NOT_EXIST", "BOT_BLOCKED", "API_ERROR", "UNKNOWN_ERROR", name="messagestatus"
			),
			server_default="Ждет отправки",
			nullable=False,
		),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.ForeignKeyConstraint(["chat_id"], ["users.id"], name=op.f("fk_messages_chat_id_users"), ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
	)
	op.create_table(
		"transactions",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.BigInteger(), nullable=True),
		sa.Column("amount", sa.Integer(), nullable=False),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
		sa.ForeignKeyConstraint(
			["user_id"], ["users.id"], name=op.f("fk_transactions_user_id_users"), ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("transactions")
	op.drop_table("messages")
	op.drop_table("awg")
	op.drop_table("users")
	# ### end Alembic commands ###
