"""increase user name to 48 chars

Revision ID: a36344c4e0fc
Revises: 0153d1dcc890
Create Date: 2025-12-07 14:17:23.414007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a36344c4e0fc"
down_revision: Union[str, Sequence[str], None] = "0153d1dcc890"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("users", schema=None) as batch_op:
		batch_op.alter_column(
			"name", existing_type=sa.VARCHAR(length=32), type_=sa.String(length=48), existing_nullable=False
		)

	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("users", schema=None) as batch_op:
		batch_op.alter_column(
			"name", existing_type=sa.String(length=48), type_=sa.VARCHAR(length=32), existing_nullable=False
		)

	# ### end Alembic commands ###
