"""make user balance nullable

Revision ID: f2c70315e75e
Revises: a36344c4e0fc
Create Date: 2025-12-08 09:22:42.773694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2c70315e75e"
down_revision: Union[str, Sequence[str], None] = "a36344c4e0fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("users", schema=None) as batch_op:
		batch_op.alter_column(
			"balance", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("'0'")
		)

	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("users", schema=None) as batch_op:
		batch_op.alter_column(
			"balance", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("'0'")
		)

	# ### end Alembic commands ###
